# Generated by Django 4.0.4 on 2022-05-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('berat', models.IntegerField()),
                ('tarif', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TarifPerKilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.IntegerField()),
            ],
        ),
    ]
