# Generated by Django 4.0.4 on 2022-05-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='tarif',
        ),
    ]
