# Generated by Django 4.0.4 on 2022-05-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_shipping_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='harga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tarifperkilo'),
        ),
    ]
