# Generated by Django 4.0.4 on 2022-05-11 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_shipping_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifperkilo',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
