# Generated by Django 4.0.4 on 2022-05-11 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_tarifperkilo_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
